"""queries added

Revision ID: 345d33be8fe8
Revises: 82561130837d
Create Date: 2021-10-09 17:23:02.683087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345d33be8fe8'
down_revision = '82561130837d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('query_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'query_amount')
    # ### end Alembic commands ###
