"""init

Revision ID: 82561130837d
Revises: 
Create Date: 2021-10-09 17:14:23.950086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82561130837d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoID', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('videoID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
